server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

security:
  secret: "SECRET"
  session-duration-minutes: 86400
  allowed-origin: "http://localhost:3000"

services:
  user:
    url: 'http://localhost:8081'
  journal:
    url: 'http://localhost:8082'
